// Catálogo fijo de descripciones por marca (CK/TH) y reglas de normalización.
// Generado desde marca-descripciones-REF.json. Fuente única — editar aquí.
// 24 marcas · 241 descripciones · 23 reglas de normalización.

/** Cada marca CK/TH → sus descripciones limpias (orden alfabético). */
export const MARCA_DESCRIPCIONES: Record<string, string[]> = {
  "CK ACCESSORIES": [
    "Men-Bags",
    "Men-Belts",
    "Men-Hats",
    "Men-Other Accessories",
    "Men-Small Leather",
    "Women-Bags",
    "Women-Hats",
    "Women-Other Accessories",
    "Women-Small Leather",
  ],
  "CK DISPLAY & PROMO": [
    "Unisex-Store Planning",
    "Unisex-Visual Merchandising",
  ],
  "CK FOOTWEAR": [
    "Men-Flip Flops",
    "Men-Sneakers",
    "Women-Flip Flops",
    "Women-Sandals",
    "Women-Sneakers",
  ],
  "CK JEANS": [
    "Men-Denim Pants",
    "Men-Dress Shirts",
    "Men-Heavyweight",
    "Men-Polos L/S",
    "Men-Polos S/S",
    "Men-Shirts Woven L/S",
    "Men-Shirts Woven S/S",
    "Men-T-Shirts L/S",
    "Men-T-Shirts S/S",
    "Women-Denim Pants",
    "Women-Dresses",
    "Women-Heavyweight",
    "Women-Other Knit Tops",
    "Women-Outerwear",
    "Women-Pant Knit",
    "Women-Pant Non-Denim",
    "Women-Shirts Woven L/S",
    "Women-Shirts Woven S/S",
    "Women-Sweaters",
    "Women-T-Shirts L/S",
    "Women-T-Shirts S/S",
  ],
  "CK KIDS": [
    "Boys-Heavyweight",
    "Boys-Pant Non-Denim",
    "Boys-Polos S/S",
    "Boys-Shirts - Woven Tops S/S",
    "Boys-Short Knit",
    "Boys-T-Shirts S/S",
    "Girls-1 Piece",
    "Girls-Denim Pants",
    "Girls-Heavyweight",
    "Girls-T-Shirts S/S",
    "Kids Unisex-T-Shirts S/S",
  ],
  "CK LEGWEAR": [
    "Men-Socks Dress",
    "Men-Socks Sport",
    "Women-Socks Sport",
  ],
  "CK MENSWEAR": [
    "Men-Heavyweight",
    "Men-Pant Knit",
    "Men-Polos L/S",
    "Men-Polos S/S",
    "Men-Shirts",
    "Men-Shirts Woven L/S",
    "Men-Shirts Woven S/S",
    "Men-Short Knit",
    "Men-Shorts Woven",
    "Men-T-Shirts L/S",
    "Men-T-Shirts S/S",
  ],
  "CK OTHER": [
    "Men-Dress Shirts",
    "Men-Shirts",
    "Women-Outerwear",
  ],
  "CK SWIMWEAR": [
    "Men-Swimshorts",
    "Men-Woven Bottoms",
  ],
  "CK UNDERWEAR": [
    "Boys-Boxer Brief",
    "Boys-Brief",
    "Boys-Polos S/S",
    "Girls-Bras",
    "Girls-Panties",
    "Men-Boxer Brief",
    "Men-Brief",
    "Men-Sleepwear",
    "Men-T-Shirts S/S",
    "Men-Trunk",
    "Men-Woven Boxers",
    "Women-Bras",
    "Women-Panties",
    "Women-Sleepwear",
  ],
  "CK WOMENSWEAR": [
    "Women-Panties",
    "Women-Shirts Woven S/S",
    "Women-Sweaters",
    "Women-T-Shirts S/S",
  ],
  "TH ACCESSORIES": [
    "Kids-Hats",
    "Men-Bags",
    "Men-Belts",
    "Men-Giftpacks",
    "Men-Hats",
    "Men-Small Leather",
    "Men-Watches",
    "Unisex-Luggage",
    "Women-Bags",
    "Women-Belts",
    "Women-Hats",
    "Women-Small Leather",
    "Women-Watches",
  ],
  "TH DISPLAY & PROMO": [
    "Unisex-Marketing",
    "Unisex-Store Planning",
  ],
  "TH FOOTWEAR": [
    "Boys-Boots",
    "Boys-Sandals",
    "Boys-Shoes",
    "Boys-Sneakers",
    "Girls-Flip Flops",
    "Girls-Sandals",
    "Girls-Shoes",
    "Girls-Sneakers",
    "Men-Flip Flops",
    "Men-Shoes",
    "Men-Sneakers",
    "Women-Flip Flops",
    "Women-Sandals",
    "Women-Shoes",
    "Women-Slippers",
    "Women-Sneakers",
  ],
  "TH HOME": [
    "Unisex-Home",
  ],
  "TH KIDS": [
    "Boys-Shirts S/S",
    "Boys-Denim Pants",
    "Boys-Giftpacks",
    "Boys-Heavyweight",
    "Boys-Outerwear",
    "Boys-Pant Knit",
    "Boys-Pant Non-Denim",
    "Boys-Polos L/S",
    "Boys-Polos S/S",
    "Boys-Shirts L/S",
    "Boys-Short Knit",
    "Boys-Shorts Denim",
    "Boys-Shorts Woven",
    "Boys-Sweaters",
    "Boys-Swimshorts",
    "Boys-T-Shirts L/S",
    "Boys-T-Shirts S/S",
    "Girls-1 Piece",
    "Girls-Denim Pants",
    "Girls-Dresses",
    "Girls-Giftpacks",
    "Girls-Heavyweight",
    "Girls-Outerwear",
    "Girls-Pant Knit",
    "Girls-Pant Non-Denim",
    "Girls-Polos S/S",
    "Girls-Shirts L/S",
    "Girls-Shorts Woven",
    "Girls-Sweaters",
    "Girls-T-Shirts S/S",
    "Kids-Hats",
    "Newborn-Bodies",
    "Newborn-Dresses",
    "Newborn-T-Shirts L/S",
    "Toddler Boys-Polos S/S",
    "Toddler Boys-Polos S/S Core",
    "Toddler Boys-T-Shirts S/S",
    "Toddler Boys-T-Shirts S/S Core",
    "Toddler Girls-T-Shirts S/S",
  ],
  "TH LEGWEAR": [
    "Kids-Socks Sport",
    "Men-Socks Sport",
    "Women-Socks Dress",
    "Women-Socks Sport",
  ],
  "TH LICENSE": [
    "Men-Socks Sport",
  ],
  "TH MENSWEAR": [
    "Men-Denim Pants",
    "Men-Hats",
    "Men-Heavyweight",
    "Men-Other Accessories",
    "Men-Outerwear",
    "Men-Pant Knit",
    "Men-Pant Non-Denim",
    "Men-Pant Non-Denim Core",
    "Men-Polos L/S",
    "Men-Polos S/S",
    "Men-Polos S/S Core",
    "Men-Shirts Woven L/S",
    "Men-Shirts Woven S/S",
    "Men-Shorts Woven",
    "Men-Sweaters",
    "Men-T-Shirts L/S",
    "Men-T-Shirts S/S",
    "Men-T-Shirts S/S Core",
    "Men-Ties / Neckwear",
  ],
  "TH OTHER": [
    "Men-Dress Shirts",
    "Men-Outerwear",
    "Men-Watches",
    "Unisex-Home",
    "Unisex-Kanine",
    "Unisex-Towels",
    "Women-Outerwear",
  ],
  "TH SWIMWEAR": [
    "Men-Swimshorts",
  ],
  "TH TOMMY JEANS": [
    "Men-Denim Pants",
    "Men-Hats",
    "Men-Heavyweight",
    "Men-Other Knit Tops",
    "Men-Outerwear",
    "Men-Polos S/S",
    "Men-Shirts Woven L/S",
    "Men-Shirts Woven S/S",
    "Men-Short Knit",
    "Men-Shorts Denim",
    "Men-T-Shirts S/S",
    "Women-Denim Pants",
    "Women-Dresses",
    "Women-Hats",
    "Women-Other Knit Tops",
    "Women-Polos S/S",
    "Women-Short Knit",
    "Women-Shorts Denim",
    "Women-Shorts Woven",
    "Women-Sweaters",
    "Women-T-Shirts L/S",
    "Women-T-Shirts S/S",
  ],
  "TH UNDERWEAR": [
    "Boys-Underwear Bottoms",
    "Men-Packs",
    "Men-Pyjamas",
    "Men-T-Shirts S/S",
    "Men-Underwear Bottoms",
    "Men-Underwear Bottoms 2PK",
    "Men-Underwear Bottoms 3PK",
    "Women-Bras",
    "Women-Panties",
    "Women-Panties 3PK",
  ],
  "TH WOMENSWEAR": [
    "Women-Blazers",
    "Women-Denim Pants",
    "Women-Denim Pants Core",
    "Women-Dress 1PC Knit",
    "Women-Dresses",
    "Women-Heavyweight",
    "Women-Other Knit Tops",
    "Women-Outerwear",
    "Women-Pant Knit",
    "Women-Pant Non-Denim",
    "Women-Polos S/S",
    "Women-Polos S/S Core",
    "Women-Shirts L/S",
    "Women-Shirts S/S",
    "Women-Shirts Woven L/S",
    "Women-Shirts Woven S/S",
    "Women-Shorts Woven",
    "Women-Sweaters",
    "Women-T-Shirts S/S",
    "Women-T-Shirts S/S Core",
    "Women-Tights",
  ],
};

/** Normalización de descripciones sucias del proveedor → descripción limpia. */
export const NORMALIZACION: Record<string, string> = {
  "BoyS Shirts S/S": "Boys Shirts S/S",
  "Boys-Polos S-S": "Boys-Polos S/S",
  "Boys-Shirts  L/S": "Boys-Shirts L/S",
  "Boys-Shirts - Woven Tops S-S": "Boys-Shirts - Woven Tops S/S",
  "Boys-T-Shirts S-S": "Boys-T-Shirts S/S",
  "Girls-Heavyweight Knits": "Girls-Heavyweight",
  "Girls-Shirts  L/S": "Girls-Shirts L/S",
  "MEN-WATCHES": "Men-Watches",
  "Men-Heavyweight Knits": "Men-Heavyweight",
  "Men-Polo S/S": "Men-Polos S/S",
  "Men-Polo S/S Core": "Men-Polos S/S Core",
  "Men-Polos L/S OFERTA": "Men-Polos L/S",
  "Men-Small Leather Goods": "Men-Small Leather",
  "Toddler Boys-Polo S/S Core": "Toddler Boys-Polos S/S Core",
  "WOMEN-WATCHES": "Women-Watches",
  "Women-Heavyweight Knits": "Women-Heavyweight",
  "Women-Panties C": "Women-Panties",
  "Women-Polo S/S Core": "Women-Polos S/S Core",
  "Women-Shirts  L/S": "Women-Shirts L/S",
  "Women-Small Leather Goods": "Women-Small Leather",
  "women-T-Shirts S/S": "Women-T-Shirts S/S",
  "Men-T-Shirts": "Men-T-Shirts S/S",
  "Girls-Panties 2PZ": "Girls-Panties",
};
