// Catálogo fijo de descripciones por marca (CK/TH/KL) y reglas de normalización.
// Espejo del Excel maestro de compras de Daniel (fuente oficial). Editar aquí.
// 26 marcas · 226 descripciones · 20 reglas de normalización.

/** Cada marca CK/TH/KL → sus descripciones limpias (orden alfabético). */
export const MARCA_DESCRIPCIONES: Record<string, string[]> = {
  "CK Accessories": [
    "Men-Bags",
    "Men-Belts",
    "Men-Hats",
    "Men-Other Accessories",
    "Men-Small Leather",
    "Women-Bags",
    "Women-Belts",
    "Women-Hats",
    "Women-Other Accessories",
    "Women-Small Leather",
  ],
  "CK Display & Promo": [
    "Unisex-Visual Merchandising",
  ],
  "CK Footwear": [
    "Boys-Sneakers",
    "Girls-Sneakers",
    "Men-Flip Flops",
    "Men-Sandals",
    "Men-Sneakers",
    "Women-Flip Flops",
    "Women-Sandals",
    "Women-Sneakers",
  ],
  "CK Jeans": [
    "Men-Denim Pants",
    "Men-Heavyweight",
    "Men-Other Knit Tops",
    "Men-Outerwear",
    "Men-Pant Non-Denim",
    "Men-Polos S/S",
    "Men-Shirts Woven L/S",
    "Men-Shirts Woven S/S",
    "Men-Shorts Denim",
    "Men-Shorts Woven",
    "Men-T-Shirts L/S",
    "Men-T-Shirts S/S",
    "Women-Denim Pants",
    "Women-Dresses",
    "Women-Heavyweight",
    "Women-Other Knit Tops",
    "Women-Outerwear",
    "Women-Pant Knit",
    "Women-Polos S/S",
    "Women-Shirts Woven L/S",
    "Women-Shirts Woven S/S",
    "Women-Shorts Denim",
    "Women-Sweaters",
    "Women-T-Shirts L/S",
    "Women-T-Shirts S/S",
  ],
  "CK Kids": [
    "Boys-Shirts Woven L/S",
    "Boys-T-Shirts S/S",
    "Girls-T-Shirts L/S",
    "Girls-T-Shirts S/S",
    "Newborn-Baby 1-Piece",
    "Newborn-T-Shirts L/S",
    "Newborn-T-Shirts S/S",
  ],
  "CK Legwear": [
    "Kids-Socks Sport",
    "Men-Socks Dress",
    "Men-Socks Sport",
    "Women-Socks Sport",
  ],
  "CK Menswear": [
    "Men-Heavyweight",
    "Men-Outerwear",
    "Men-Pant Non-Denim",
    "Men-Polos S/S",
    "Men-Shirts Woven L/S",
    "Men-Shirts Woven S/S",
    "Men-T-Shirts L/S",
    "Men-T-Shirts S/S",
  ],
  "CK Other": [
    "Men-Dress Shirts",
    "Men-Outerwear",
    "Women-Outerwear",
  ],
  "CK Performance": [
    "Men-Outerwear",
    "Men-Pant Knit",
    "Men-Shorts Woven",
    "Men-T-Shirts S/S",
    "Women-Bras",
    "Women-Outerwear",
    "Women-Short Knit",
    "Women-T-Shirts S/S",
    "Women-Tights",
  ],
  "CK Swimwear": [
    "Men-Swimshorts",
    "Women-1 Piece",
  ],
  "CK Underwear": [
    "Boys-Boxer Brief",
    "Men-Boxer Brief",
    "Men-Brief",
    "Men-Sleepwear",
    "Men-T-Shirts",
    "Men-Trunk",
    "Men-Woven Boxers",
    "Women-Bras",
    "Women-Panties",
    "Women-Shapewear",
    "Women-Sleepwear",
  ],
  "CK Womenswear": [
    "Women-Heavyweight",
    "Women-T-Shirts S/S",
  ],
  "KL Accessories": [
    "Women-Bags",
    "Women-Small Leather",
  ],
  "KL Footwear": [
    "Women-Flip Flops",
    "Women-Sneakers",
  ],
  "KL Menswear": [
    "Men-T-Shirts S/S",
  ],
  "KL Womenswear": [
    "Women-T-Shirts S/S",
  ],
  "TH Accessories": [
    "Men-Bags",
    "Men-Belts",
    "Men-Giftpacks",
    "Men-Hats",
    "Men-Small Leather",
    "Women-Bags",
    "Women-Belts",
    "Women-Giftpacks",
    "Women-Hats",
    "Women-Small Leather",
  ],
  "TH Footwear": [
    "Boys-Flip Flops",
    "Boys-Sandals",
    "Boys-Shoes",
    "Boys-Sneakers",
    "Girls-Flip Flops",
    "Girls-Sandals",
    "Girls-Shoes",
    "Girls-Sneakers",
    "Men-Flip Flops",
    "Men-Sandals",
    "Men-Shoes",
    "Men-Sneakers",
    "Women-Flip Flops",
    "Women-Sandals",
    "Women-Shoes",
    "Women-Sneakers",
  ],
  "TH Kids": [
    "Boys-Denim Pants",
    "Boys-Giftpacks",
    "Boys-Other Knit Tops",
    "Boys-Outerwear",
    "Boys-Pant Non-Denim",
    "Boys-Polos S/S",
    "Boys-Polos S/S Core",
    "Boys-Shirts Woven L/S",
    "Boys-Shorts Woven",
    "Boys-Sweaters",
    "Boys-T-Shirts S/S",
    "Boys-T-Shirts S/S Core",
    "Girls-Denim Pants",
    "Girls-Dresses",
    "Girls-Other Knit Tops",
    "Girls-Outerwear",
    "Girls-Polos S/S",
    "Girls-Shorts Woven",
    "Girls-Sweaters",
    "Girls-T-Shirts S/S",
    "Newborn-Baby 1-Piece",
    "Newborn-Baby 2-Piece",
    "Newborn-Bodies",
    "Newborn-Dresses",
    "Newborn-Giftpacks",
    "Newborn-Pant Knit",
    "Newborn-Sweaters",
    "Newborn-T-Shirts S/S",
    "Toddler Boys-Polos S/S Core",
    "Toddler Boys-T-Shirts S/S",
    "Toddler Boys-T-Shirts S/S Core",
  ],
  "TH Legwear": [
    "Kids-Socks Sport",
    "Men-Socks Dress",
    "Men-Socks Sport",
    "Women-Socks Sport",
  ],
  "TH Menswear": [
    "Men-Denim Pants",
    "Men-Heavyweight",
    "Men-Other Accessories",
    "Men-Outerwear",
    "Men-Pant Non-Denim",
    "Men-Pant Non-Denim Core",
    "Men-Polo S/S Core",
    "Men-Polos S/S",
    "Men-Shirts Woven L/S",
    "Men-Shirts Woven S/S",
    "Men-Shorts Woven",
    "Men-Sweaters",
    "Men-Swimshorts",
    "Men-T-Shirts S/S",
    "Men-T-Shirts S/S Core",
  ],
  "TH Other": [
    "Men-Dress Shirts",
    "Men-Outerwear",
    "Unisex-Home Towels",
    "Women-Outerwear",
  ],
  "TH Swimwear": [
    "Men-Swimshorts",
  ],
  "TH Tommy Jeans": [
    "Men-Denim Pants",
    "Men-Outerwear",
    "Men-Polos S/S",
    "Men-Shirts Woven L/S",
    "Men-Shirts Woven S/S",
    "Men-Shorts Denim",
    "Men-Shorts Woven",
    "Men-T-Shirts S/S",
    "Women-Denim Pants",
    "Women-Dresses",
    "Women-Heavyweight",
    "Women-Other Knit Tops",
    "Women-Outerwear",
    "Women-Pant Knit",
    "Women-Pant Non-Denim",
    "Women-Polos S/S",
    "Women-Shirts Woven L/S",
    "Women-Shirts Woven S/S",
    "Women-Shorts Denim",
    "Women-Shorts Woven",
    "Women-Skirts",
    "Women-Sweaters",
    "Women-T-Shirts L/S",
    "Women-T-Shirts S/S",
  ],
  "TH Underwear": [
    "Men-Packs",
    "Men-T-Shirts S/S",
    "Men-Underwear Bottoms",
    "Women-Bras",
    "Women-Coordinate Panties",
  ],
  "TH Womenswear": [
    "Women-Blazers",
    "Women-Denim Pants",
    "Women-Denim Pants Core",
    "Women-Dress 1PC Knit",
    "Women-Heavyweight",
    "Women-Other Knit Tops",
    "Women-Outerwear",
    "Women-Pant Knit",
    "Women-Pant Non-Denim",
    "Women-Polo S/S Core",
    "Women-Polos S/S",
    "Women-Shirts Woven L/S",
    "Women-Shirts Woven L/S Core",
    "Women-Shirts Woven S/S",
    "Women-Shorts Denim",
    "Women-Shorts Woven",
    "Women-Skirts",
    "Women-Sweaters",
    "Women-T-Shirts S/S",
    "Women-T-Shirts S/S Core",
  ],
};

/** Normalización de descripciones sucias del proveedor → descripción limpia. */
export const NORMALIZACION: Record<string, string> = {
  "BoyS Shirts S/S": "Boys Shirts S/S",
  "Boys-Polos S-S": "Boys-Polos S/S",
  "Boys-Shirts  L/S": "Boys-Shirts L/S",
  "Boys-Shirts - Woven Tops S-S": "Boys-Shirts - Woven Tops S/S",
  "Boys-T-Shirts S-S": "Boys-T-Shirts S/S",
  "Girls-Heavyweight Knits": "Girls-Heavyweight",
  "Girls-Shirts  L/S": "Girls-Shirts L/S",
  "MEN-WATCHES": "Men-Watches",
  "Men-Heavyweight Knits": "Men-Heavyweight",
  "Men-Polo S/S": "Men-Polos S/S",
  "Men-Polos L/S OFERTA": "Men-Polos L/S",
  "Men-Small Leather Goods": "Men-Small Leather",
  "WOMEN-WATCHES": "Women-Watches",
  "Women-Blazers / Sports Jackets": "Women-Blazers",
  "Women-Heavyweight Knits": "Women-Heavyweight",
  "Women-Panties C": "Women-Panties",
  "Women-Shirts  L/S": "Women-Shirts L/S",
  "Women-Small Leather Goods": "Women-Small Leather",
  "women-T-Shirts S/S": "Women-T-Shirts S/S",
  "Girls-Panties 2PZ": "Girls-Panties",
};
