-- ─────────────────────────────────────────────────────────────────────────────
-- Catálogo de descripciones por marca del Depurador de Productos
-- (/productos/cargar). La tabla es LA fuente de verdad: reemplaza la constante
-- MARCA_DESCRIPCIONES que vivía hardcodeada en
-- src/lib/depurador/marca-descripciones.ts (26 marcas, 227 descripciones).
--
-- Flujo: cuando el Depurador o Facturas Tienda detectan una descripción NUEVA
-- (no catalogada), admin/secretaria pueden aprobarla desde la app y queda
-- insertada aquí con origen = 'aprobada' y auditoría de quién y cuándo.
-- Desactivar (activa = false) NO borra: el histórico queda.
--
-- IMPORTANTE: correr esta DDL ANTES de deployar el código que la usa — sin la
-- tabla, el catálogo no carga y el Depurador queda bloqueado a propósito
-- (sin fallback al archivo TS).
--
-- Migración ADITIVA e idempotente (create if not exists + seed con
-- on conflict do nothing).
-- ─────────────────────────────────────────────────────────────────────────────

create table if not exists depurador_descripciones (
  id           uuid primary key default gen_random_uuid(),
  marca        text not null,
  descripcion  text not null,
  activa       boolean not null default true,
  origen       text not null default 'seed' check (origen in ('seed', 'aprobada')),
  aprobada_por text,
  aprobada_at  timestamptz,
  created_at   timestamptz not null default now()
);

-- Unicidad marca + descripción, insensible a caja (los Excel traen mayúsculas).
create unique index if not exists idx_depurador_descripciones_key
  on depurador_descripciones (lower(marca), lower(descripcion));

alter table depurador_descripciones enable row level security;

-- Lectura para todos los roles (datos no sensibles, API ya auth-gated).
-- Escritura solo service_role (la API server-side).
drop policy if exists public_read on depurador_descripciones;
create policy public_read on depurador_descripciones
  for select
  using (true);

drop policy if exists service_role_all on depurador_descripciones;
create policy service_role_all
  on depurador_descripciones
  as permissive
  for all
  to service_role
  using (true)
  with check (true);

-- ─────────────────────────────────────────────────────────────────────────────
-- SEED: las 227 descripciones actuales de MARCA_DESCRIPCIONES (26 marcas),
-- generadas programáticamente desde el archivo TS. origen = 'seed' (default).
-- ─────────────────────────────────────────────────────────────────────────────

insert into depurador_descripciones (marca, descripcion) values
  ('CK Accessories', 'Men-Bags'),
  ('CK Accessories', 'Men-Belts'),
  ('CK Accessories', 'Men-Hats'),
  ('CK Accessories', 'Men-Other Accessories'),
  ('CK Accessories', 'Men-Small Leather'),
  ('CK Accessories', 'Women-Bags'),
  ('CK Accessories', 'Women-Belts'),
  ('CK Accessories', 'Women-Hats'),
  ('CK Accessories', 'Women-Other Accessories'),
  ('CK Accessories', 'Women-Small Leather'),
  ('CK Display & Promo', 'Unisex-Visual Merchandising'),
  ('CK Footwear', 'Boys-Sneakers'),
  ('CK Footwear', 'Girls-Sneakers'),
  ('CK Footwear', 'Men-Flip Flops'),
  ('CK Footwear', 'Men-Sandals'),
  ('CK Footwear', 'Men-Sneakers'),
  ('CK Footwear', 'Women-Flip Flops'),
  ('CK Footwear', 'Women-Sandals'),
  ('CK Footwear', 'Women-Sneakers'),
  ('CK Jeans', 'Men-Denim Pants'),
  ('CK Jeans', 'Men-Dress Shirts'),
  ('CK Jeans', 'Men-Heavyweight'),
  ('CK Jeans', 'Men-Other Knit Tops'),
  ('CK Jeans', 'Men-Outerwear'),
  ('CK Jeans', 'Men-Pant Non-Denim'),
  ('CK Jeans', 'Men-Polos S/S'),
  ('CK Jeans', 'Men-Shirts Woven L/S'),
  ('CK Jeans', 'Men-Shirts Woven S/S'),
  ('CK Jeans', 'Men-Shorts Denim'),
  ('CK Jeans', 'Men-Shorts Woven'),
  ('CK Jeans', 'Men-T-Shirts L/S'),
  ('CK Jeans', 'Men-T-Shirts S/S'),
  ('CK Jeans', 'Women-Denim Pants'),
  ('CK Jeans', 'Women-Dresses'),
  ('CK Jeans', 'Women-Heavyweight'),
  ('CK Jeans', 'Women-Other Knit Tops'),
  ('CK Jeans', 'Women-Outerwear'),
  ('CK Jeans', 'Women-Pant Knit'),
  ('CK Jeans', 'Women-Polos S/S'),
  ('CK Jeans', 'Women-Shirts Woven L/S'),
  ('CK Jeans', 'Women-Shirts Woven S/S'),
  ('CK Jeans', 'Women-Shorts Denim'),
  ('CK Jeans', 'Women-Sweaters'),
  ('CK Jeans', 'Women-T-Shirts L/S'),
  ('CK Jeans', 'Women-T-Shirts S/S'),
  ('CK Kids', 'Boys-Shirts Woven L/S'),
  ('CK Kids', 'Boys-T-Shirts S/S'),
  ('CK Kids', 'Girls-T-Shirts L/S'),
  ('CK Kids', 'Girls-T-Shirts S/S'),
  ('CK Kids', 'Newborn-Baby 1-Piece'),
  ('CK Kids', 'Newborn-T-Shirts L/S'),
  ('CK Kids', 'Newborn-T-Shirts S/S'),
  ('CK Legwear', 'Kids-Socks Sport'),
  ('CK Legwear', 'Men-Socks Dress'),
  ('CK Legwear', 'Men-Socks Sport'),
  ('CK Legwear', 'Women-Socks Sport'),
  ('CK Menswear', 'Men-Heavyweight'),
  ('CK Menswear', 'Men-Outerwear'),
  ('CK Menswear', 'Men-Pant Non-Denim'),
  ('CK Menswear', 'Men-Polos S/S'),
  ('CK Menswear', 'Men-Shirts Woven L/S'),
  ('CK Menswear', 'Men-Shirts Woven S/S'),
  ('CK Menswear', 'Men-T-Shirts L/S'),
  ('CK Menswear', 'Men-T-Shirts S/S'),
  ('CK Other', 'Men-Dress Shirts'),
  ('CK Other', 'Men-Outerwear'),
  ('CK Other', 'Women-Outerwear'),
  ('CK Performance', 'Men-Outerwear'),
  ('CK Performance', 'Men-Pant Knit'),
  ('CK Performance', 'Men-Shorts Woven'),
  ('CK Performance', 'Men-T-Shirts S/S'),
  ('CK Performance', 'Women-Bras'),
  ('CK Performance', 'Women-Outerwear'),
  ('CK Performance', 'Women-Short Knit'),
  ('CK Performance', 'Women-T-Shirts S/S'),
  ('CK Performance', 'Women-Tights'),
  ('CK Swimwear', 'Men-Swimshorts'),
  ('CK Swimwear', 'Women-1 Piece'),
  ('CK Underwear', 'Boys-Boxer Brief'),
  ('CK Underwear', 'Men-Boxer Brief'),
  ('CK Underwear', 'Men-Brief'),
  ('CK Underwear', 'Men-Sleepwear'),
  ('CK Underwear', 'Men-T-Shirts'),
  ('CK Underwear', 'Men-Trunk'),
  ('CK Underwear', 'Men-Woven Boxers'),
  ('CK Underwear', 'Women-Bras'),
  ('CK Underwear', 'Women-Panties'),
  ('CK Underwear', 'Women-Shapewear'),
  ('CK Underwear', 'Women-Sleepwear'),
  ('CK Womenswear', 'Women-Heavyweight'),
  ('CK Womenswear', 'Women-T-Shirts S/S'),
  ('KL Accessories', 'Women-Bags'),
  ('KL Accessories', 'Women-Small Leather'),
  ('KL Footwear', 'Women-Flip Flops'),
  ('KL Footwear', 'Women-Sneakers'),
  ('KL Menswear', 'Men-T-Shirts S/S'),
  ('KL Womenswear', 'Women-T-Shirts S/S'),
  ('TH Accessories', 'Men-Bags'),
  ('TH Accessories', 'Men-Belts'),
  ('TH Accessories', 'Men-Giftpacks'),
  ('TH Accessories', 'Men-Hats'),
  ('TH Accessories', 'Men-Small Leather'),
  ('TH Accessories', 'Women-Bags'),
  ('TH Accessories', 'Women-Belts'),
  ('TH Accessories', 'Women-Giftpacks'),
  ('TH Accessories', 'Women-Hats'),
  ('TH Accessories', 'Women-Small Leather'),
  ('TH Footwear', 'Boys-Flip Flops'),
  ('TH Footwear', 'Boys-Sandals'),
  ('TH Footwear', 'Boys-Shoes'),
  ('TH Footwear', 'Boys-Sneakers'),
  ('TH Footwear', 'Girls-Flip Flops'),
  ('TH Footwear', 'Girls-Sandals'),
  ('TH Footwear', 'Girls-Shoes'),
  ('TH Footwear', 'Girls-Sneakers'),
  ('TH Footwear', 'Men-Flip Flops'),
  ('TH Footwear', 'Men-Sandals'),
  ('TH Footwear', 'Men-Shoes'),
  ('TH Footwear', 'Men-Sneakers'),
  ('TH Footwear', 'Women-Flip Flops'),
  ('TH Footwear', 'Women-Sandals'),
  ('TH Footwear', 'Women-Shoes'),
  ('TH Footwear', 'Women-Sneakers'),
  ('TH Kids', 'Boys-Denim Pants'),
  ('TH Kids', 'Boys-Giftpacks'),
  ('TH Kids', 'Boys-Other Knit Tops'),
  ('TH Kids', 'Boys-Outerwear'),
  ('TH Kids', 'Boys-Pant Non-Denim'),
  ('TH Kids', 'Boys-Polos S/S'),
  ('TH Kids', 'Boys-Polos S/S Core'),
  ('TH Kids', 'Boys-Shirts Woven L/S'),
  ('TH Kids', 'Boys-Shorts Woven'),
  ('TH Kids', 'Boys-Sweaters'),
  ('TH Kids', 'Boys-T-Shirts S/S'),
  ('TH Kids', 'Boys-T-Shirts S/S Core'),
  ('TH Kids', 'Girls-Denim Pants'),
  ('TH Kids', 'Girls-Dresses'),
  ('TH Kids', 'Girls-Other Knit Tops'),
  ('TH Kids', 'Girls-Outerwear'),
  ('TH Kids', 'Girls-Polos S/S'),
  ('TH Kids', 'Girls-Shorts Woven'),
  ('TH Kids', 'Girls-Sweaters'),
  ('TH Kids', 'Girls-T-Shirts S/S'),
  ('TH Kids', 'Newborn-Baby 1-Piece'),
  ('TH Kids', 'Newborn-Baby 2-Piece'),
  ('TH Kids', 'Newborn-Bodies'),
  ('TH Kids', 'Newborn-Dresses'),
  ('TH Kids', 'Newborn-Giftpacks'),
  ('TH Kids', 'Newborn-Pant Knit'),
  ('TH Kids', 'Newborn-Sweaters'),
  ('TH Kids', 'Newborn-T-Shirts S/S'),
  ('TH Kids', 'Toddler Boys-Polos S/S Core'),
  ('TH Kids', 'Toddler Boys-T-Shirts S/S'),
  ('TH Kids', 'Toddler Boys-T-Shirts S/S Core'),
  ('TH Legwear', 'Kids-Socks Sport'),
  ('TH Legwear', 'Men-Socks Dress'),
  ('TH Legwear', 'Men-Socks Sport'),
  ('TH Legwear', 'Women-Socks Sport'),
  ('TH Menswear', 'Men-Denim Pants'),
  ('TH Menswear', 'Men-Heavyweight'),
  ('TH Menswear', 'Men-Other Accessories'),
  ('TH Menswear', 'Men-Outerwear'),
  ('TH Menswear', 'Men-Pant Non-Denim'),
  ('TH Menswear', 'Men-Pant Non-Denim Core'),
  ('TH Menswear', 'Men-Polo S/S Core'),
  ('TH Menswear', 'Men-Polos S/S'),
  ('TH Menswear', 'Men-Shirts Woven L/S'),
  ('TH Menswear', 'Men-Shirts Woven S/S'),
  ('TH Menswear', 'Men-Shorts Woven'),
  ('TH Menswear', 'Men-Sweaters'),
  ('TH Menswear', 'Men-Swimshorts'),
  ('TH Menswear', 'Men-T-Shirts S/S'),
  ('TH Menswear', 'Men-T-Shirts S/S Core'),
  ('TH Other', 'Men-Dress Shirts'),
  ('TH Other', 'Men-Outerwear'),
  ('TH Other', 'Unisex-Home Towels'),
  ('TH Other', 'Women-Outerwear'),
  ('TH Swimwear', 'Men-Swimshorts'),
  ('TH Tommy Jeans', 'Men-Denim Pants'),
  ('TH Tommy Jeans', 'Men-Outerwear'),
  ('TH Tommy Jeans', 'Men-Polos S/S'),
  ('TH Tommy Jeans', 'Men-Shirts Woven L/S'),
  ('TH Tommy Jeans', 'Men-Shirts Woven S/S'),
  ('TH Tommy Jeans', 'Men-Shorts Denim'),
  ('TH Tommy Jeans', 'Men-Shorts Woven'),
  ('TH Tommy Jeans', 'Men-T-Shirts S/S'),
  ('TH Tommy Jeans', 'Women-Denim Pants'),
  ('TH Tommy Jeans', 'Women-Dresses'),
  ('TH Tommy Jeans', 'Women-Heavyweight'),
  ('TH Tommy Jeans', 'Women-Other Knit Tops'),
  ('TH Tommy Jeans', 'Women-Outerwear'),
  ('TH Tommy Jeans', 'Women-Pant Knit'),
  ('TH Tommy Jeans', 'Women-Pant Non-Denim'),
  ('TH Tommy Jeans', 'Women-Polos S/S'),
  ('TH Tommy Jeans', 'Women-Shirts Woven L/S'),
  ('TH Tommy Jeans', 'Women-Shirts Woven S/S'),
  ('TH Tommy Jeans', 'Women-Shorts Denim'),
  ('TH Tommy Jeans', 'Women-Shorts Woven'),
  ('TH Tommy Jeans', 'Women-Skirts'),
  ('TH Tommy Jeans', 'Women-Sweaters'),
  ('TH Tommy Jeans', 'Women-T-Shirts L/S'),
  ('TH Tommy Jeans', 'Women-T-Shirts S/S'),
  ('TH Underwear', 'Men-Packs'),
  ('TH Underwear', 'Men-T-Shirts S/S'),
  ('TH Underwear', 'Men-Underwear Bottoms'),
  ('TH Underwear', 'Women-Bras'),
  ('TH Underwear', 'Women-Coordinate Panties'),
  ('TH Womenswear', 'Women-Blazers'),
  ('TH Womenswear', 'Women-Denim Pants'),
  ('TH Womenswear', 'Women-Denim Pants Core'),
  ('TH Womenswear', 'Women-Dress 1PC Knit'),
  ('TH Womenswear', 'Women-Heavyweight'),
  ('TH Womenswear', 'Women-Other Knit Tops'),
  ('TH Womenswear', 'Women-Outerwear'),
  ('TH Womenswear', 'Women-Pant Knit'),
  ('TH Womenswear', 'Women-Pant Non-Denim'),
  ('TH Womenswear', 'Women-Polo S/S Core'),
  ('TH Womenswear', 'Women-Polos S/S'),
  ('TH Womenswear', 'Women-Shirts Woven L/S'),
  ('TH Womenswear', 'Women-Shirts Woven L/S Core'),
  ('TH Womenswear', 'Women-Shirts Woven S/S'),
  ('TH Womenswear', 'Women-Shorts Denim'),
  ('TH Womenswear', 'Women-Shorts Woven'),
  ('TH Womenswear', 'Women-Skirts'),
  ('TH Womenswear', 'Women-Sweaters'),
  ('TH Womenswear', 'Women-T-Shirts S/S'),
  ('TH Womenswear', 'Women-T-Shirts S/S Core')
on conflict ((lower(marca)), (lower(descripcion))) do nothing;
